#!/usr/bin/env python
#coding:gbk
#Copyright (C) dirlt

import os
import glob
env=Environment(CPPPATH=['../../'],
                CXXFLAGS='-W -Wall -g -Wno-unused-parameter -Werror -DDEBUG -fPIC',
                LIBPATH=['../'],
                LIBS=['common',
                      'rt',                
                      'pthread'])

for x in glob.glob('*.cc'):
    env.Program(os.path.splitext(x)[0]+'.exe',[x])
