* remote
#+TITLE: Remote

http://jianshu.io/notebooks/41672/latest

-----

远程工作的关键是：独处以进行深度地思考。当你一个人工作，远离总部的吵杂，你将会很快进入工作状态，迅速地完成工作。是的，那些你在总部的正常办公时间无法完成的工作。当然，远程办公也有很多挑战。即使独处，你也可能被来自其他方面的影响打断。如果在家，可能被电视机打断。如果在咖啡馆，可能被隔壁桌吵闹的讨论声打扰。但是关键是：这些因素是我们可以控制的。你可以选择一个适合你自己的工作环境。你可以带上耳机而不必在意另外一个协同办公的同事在你身边游荡。同样，你也不必在意会被打扰而去参加一个临时出现而又无关紧要的会议。你的工作环境，工作氛围，是你自己的。

除了工作场地之外，在工作时间上，人们逐渐也由同步时间模式转变为异步时间模式。是的，我们不但不需要被困在一个固定的地方一起工作，我们甚至不需要在同一个时间段内一起工作。当然，不是所有的工作都能在完全没有约束的情况下完成。在37Signals，我们的客户团队是按照美国当地时间为客户提供服务的，所以我们必须保证他们必须按照这个时间段正常工作。摆脱即有的朝九晚五的工作时间观念。这个过程肯定需要花点时间。但是很快你将会发现，我们真正需要关心的是所完成工作的质量，而不是完成这些工作的地点或者时间段。

人们普遍认为，只有在湾区，才能找到最优秀的开发人员。而事实上，我们在那儿一名员工也没有，这个结果并不是我们有意为之。但是我们觉得整个湾区的创业和投资环境有些浮躁，程序员们每天都会面对层出不穷的新公司，并且收到他们的招聘需求。在这种环境下，很难安心地工作。如果在你的员工周围，每天都会出现更有挑战性的工作机会，那么频繁地跳槽也不会是一件意外的事情。我们发现，公司里的明星员工，往往能够远离周边浮躁的环境的影响，集中精力在自己的事情上。而他们，往往工作地也更加快乐。

远程办公的初衷：是为了提供员工的生活质量。同时能够雇佣来自全球各地最优秀的员工。当然，如果采用远程办公，可能也会带来办公室租金费用的削减，人员开支的削减 （数量更少但是效率更高的员工）。但是这些只是附带的结果，并不是我们采取远程办公这种模式的初衷。此外，一般我们认为最适合远程办公的工作有：写作、编程、设计、广告、客服等。暂时在大规模制造业当中，远程办公没有什么可做的。工作的目的，不是为了将所有员工聚集到一个房间，在同一个时间段内压榨他们的劳动力。这样的话，员工们工作的并不快乐，工作的产出也很一般。让他们自由选择一个良好的工作环境，保持愉快的心情，好的结果也是顺理成章的事情。

在远程办公的初期，你可能会感觉周围没有其他同事一起工作是一种解脱。但是从长期来看，你可能也会失去一些东西。例如，当你想讨论一件事情的时候，发现身边没有同事可以与你头脑风暴，或者争论。另外，由于没有硬性的规章制度和监督，所以每个实行远程办公的同事，自己都需要有很高的自觉性和责任感。对于很多有拖延症的人来说，这点很难做到。

-----

大部分好的解决方案，是在实际工作中产生的。是根据过去6个月、甚至6年实际的操作经验总结后得出的。单单希望大家聚拢在一起头脑风暴，是无法产生好的解决方案的。另外，过多的头脑风暴，只会伤害你自己和你的团队。一次新的头脑风暴，意味着否定上一次头脑风暴所产生的结论。那些时间被浪费了，而那些所谓的新创意又不断被叠加累积。这就是为什么在37Signals，我们不经常面对面讨论。我们认为，在进行一次真正的面对面交流之前，我们需要事先就把问题思考清楚。所以，每年只有3次的时间，我们会在芝加哥的总部聚会。

大部分人不敢于尝试远程办公，原因在于缺乏信任。老板们会担忧： 如果我不呆在员工身边的话，他们会认真工作吗？他们会不会整天上网聊天，或者溜出去玩视频游戏？然而实际情况是：如果你的员工真是要上网聊天或者玩游戏，那即使他们在自己办公室的座位上，也会偷偷这么做的。懒惰是一种天性，你不能总是幻想所有员工都会120%专心投入工作。所有员工都非常敬业，对于每一件小事都要求近乎完美。如果你必须要时刻监督和看管着你的员工，那么你只是个保姆，不是管理人员。你的问题在于招聘了错误的员工，无论是否采用远程办公，他们都不会高效地工作。

问题的本质是，不要录用那些你不信任的人。同样，不要为那些不信任你的老板工作。如果老板们不相信你会敬业地在远程办公，在其他事情上他会相信你吗？作为老板，你要么信任现在与你共事的员工。要么尝试去寻找那些你愿意相信的员工。

有些时候，如果你被其他的一些事情分心。这反而是一个很好的机会，反思一下你的工作是否没有被分配好，或者被分配到的工作内容太微小，甚至正在做的工作是不是完全没有意义。与其把时间花在电视游戏或者肥皂剧上，是否应该花时间思考一下这些问题。如果不是工作内容本身的问题，房间环境对人的潜意识也有一定影响。如果你身在厨房，可能潜意识里会想清理水槽。如果你坐在客厅的沙发上，可能潜意识里会去拿遥控器开电视。所以，如果你身在一件封闭的办公室内，你可能会自动进入想要工作的状态。如果以上这两点，都不是影响你在家办公效率低下的主要原因。你也可以尝试在家以外的地方办公。你可以在咖啡馆、图书馆或者公园内办公。大部分人都希望能够正常工作，只要工作充满刺激和意义。但是如果你被困在工作的死胡同里，呆在办公桌前感觉完全没有意义。那么你需要的完全不是更换一种工作方式，你需要的是一份新的工作。

传统公司内部一般效率低下，而且盛行官僚主义，但是外表看上去都运转良好。原因是，一旦一家公司有了稳定的带来现金流的业务，一般他们不会在意为了这项业务需要招聘多少员工或者有多少低效的员工在其中。所以在大型公司内部推行节省时间促进效率的新技术是不现实的。他们在意更多的是利润，以及如何保持这种利润，而不是需要投入多少人力成本，以及人力投入性价比的高低。

你所唯一需要的，就是保持自信。相信你正在使用一种更加聪明的方式工作，即使大部分人都还没意识到这一点。相信所有创新的产品，在初期看上去都很疯狂，之后才慢慢被大众接受。相信远程办公也是一种创新，当越来越多的人尝试远程办公，它也将慢慢变成大家都认同的办公方式。所以不要等待，现在就开始吧。

当工作结果能实时展示在所有人面前的时候，我们就能在短时间内判断一个人是否聪明和高效了。如果项目在操作过程中总是遇到这样或那样的问题，说明这个人对手头上的工作并没有很熟练或在行。如果某些人的项目经常性发生拖延，那么他的效率就有待提高。通过远程的方式，你就能很快识别出那些真正优秀的员工。能够快速学习，并且产生实际成果的人。快速识别并且留住这些人，让其他不适应远程的平庸的员工离开公司。

不是所有的员工都要聚集在一个办公室内才能创造出良好的公司文化。真正的文化来源于所有员工的实际做法。新的员工来到公司，自然而然会观察内部是如何运作的，老员工如何上班，决策是如何被做出的，问题是如何被解决的。之后，他们自然而然也会效仿。

-----

