#!/usr/bin/env python
#coding:utf-8
#Copyright (C) dirlt

import hashlib
import sys
import os

def main(dir):
    fs = os.listdir(dir)
    d = {}
    for f in fs:
        path = os.path.join(dir,f)
        if os.path.isdir(path):
            continue
        data = open(path).read()
        m = hashlib.md5()
        m.update(data)
        sig = m.hexdigest()
        if sig in d:
            d[sig].append(f)
        else:
            d[sig] = [f]
    for f in d.keys():
        v = d[f]
        if len(v) >= 2:
            print v

if __name__ == '__main__':
    if(len(sys.argv)!=2):
        print 'Find DUPlicated files'
        print 'usage:%s directory'%(sys.argv[0])
    else:
        dir=sys.argv[1]
        main(dir)
                
    
