#!/bin/bash
wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add - 
sudo apt-add-repository "deb http://dl.google.com/linux/chrome/deb/ stable main"

wget -q -O - http://download.virtualbox.org/virtualbox/debian/oracle_vbox.asc -O- | sudo apt-key add -
sudo apt-add-repository "deb http://download.virtualbox.org/virtualbox/debian raring contrib"
sudo apt-add-repository "deb http://download.virtualbox.org/virtualbox/debian quantal contrib"
sudo apt-add-repository "deb http://download.virtualbox.org/virtualbox/debian precise contrib"
sudo apt-add-repository "deb http://download.virtualbox.org/virtualbox/debian oneiric contrib"
sudo apt-add-repository "deb http://download.virtualbox.org/virtualbox/debian natty contrib"
sudo apt-add-repository "deb http://download.virtualbox.org/virtualbox/debian maverick contrib non-free"
sudo apt-add-repository "deb http://download.virtualbox.org/virtualbox/debian lucid contrib non-free"
sudo apt-add-repository "deb http://download.virtualbox.org/virtualbox/debian karmic contrib non-free"
sudo apt-add-repository "deb http://download.virtualbox.org/virtualbox/debian hardy contrib non-free"
sudo apt-add-repository "deb http://download.virtualbox.org/virtualbox/debian wheezy contrib"
sudo apt-add-repository "deb http://download.virtualbox.org/virtualbox/debian squeeze contrib non-free"
sudo apt-add-repository "deb http://download.virtualbox.org/virtualbox/debian lenny contrib non-free"
sudo apt-add-repository "deb http://ppa.launchpad.net/tualatrix/ppa/ubuntu precise main"

sudo apt-add-repository "deb http://archive.canonical.com/ $(lsb_release -sc) partner"

sudo apt-get update

