#!/bin/bash

# build environment.
rm -f /tmp/ubuntu-backup
ln -s "/media/Expansion Drive/Ubuntu Backup/" /tmp/ubuntu-backup

# check condition.
pwd=`pwd`
if [ ! -d "$pwd/dirlt" ]
then
    echo "Are you at right directory???"
    exit 1
fi

# determine source and destination.
base=`basename "$pwd"`
home=/home/dirlt/
backup=/tmp/ubuntu-backup/dirlt

if [ "X$base" = "Xhome" ]
then
    src=$backup
    dst=$home
else
    src=$home
    dst=$backup
fi

echo "$src ---> $dst"
    
# do rsync.

# packages.
mkdir -p "$dst/utils"
pkgs=`find $src/utils/ -maxdepth 1 -type f`
for p in $pkgs
do
    echo "$p..."
    p=`basename $p`
    rsync -az --no-times $src/utils/$p $dst/utils/$p
done

# directories
for d in share .m2
do
    echo "$d..."
    rsync -arz --no-times "$src/$d/" "$dst/$d/"
done

# virtual machine
VM=$1
shift 1
if [ $VM"x" == "--vmx" ]
then
    d="VirtualBox VMs"
    echo "$d..."
    rsync -arz --no-times "$src/$d/" "$dst/$d/"
fi
