#!/bin/bash

# build environment.
rm -f /tmp/ubuntu-backup
ln -s "/media/Expansion Drive/Ubuntu Backup/" /tmp/ubuntu-backup

# check condition.
pwd=`pwd`
if [ ! -d "$pwd/dirlt" ]
then
    echo "Are you at right directory???"
    exit 1
fi

# determine source and destination.
base=`basename "$pwd"`
home=/home/dirlt/
backup=/tmp/ubuntu-backup/dirlt

if [ "X$base" = "Xhome" ]
then
    src=$backup
    dst=$home
else
    src=$home
    dst=$backup
fi

echo "$src ---> $dst"
    
# do rsync.

function sync_dir() {
    d=$1    
    mkdir -p "$dst/$d/"
    echo "sync $d..."
    rsync -arz --no-times "$src/$d/" "$dst/$d/"    
}

function sync_utils() {
    mkdir -p "$dst/utils"
    pkgs=`find $src/utils/ -maxdepth 1 -type f`
    for p in $pkgs
    do
	echo "sync $p..."
	p=`basename $p`
	rsync -az --no-times $src/utils/$p $dst/utils/$p
    done
}

UTILS="yes"
SHARE="yes"
M2="yes"
VM="no"

while test $# -gt 0
do
    case $1 in 
	--utils)
	    UTILS="yes"
	    ;;
	--share)
	    SHARE="yes"
	    ;;
	--m2)
	    M2="yes"
	    ;;
	--vm)
	    VM="yes"
	    ;;
    esac
    shift 1
done

if [ $UTILS == "yes" ] ; then sync_utils ; fi
if [ $SHARE == "yes" ] ; then sync_dir "share" ; fi
if [ $M2 == "yes" ] ; then sync_dir ".m2" ; fi
if [ $VM == "yes" ] ; then sync_dir "VirtualBox VMs" fi
