#!/usr/bin/env python
#coding:utf-8
#Copyright (C) dirlt

PAC="""function FindProxyForURL(url, host){
    var TUNNEL_PROXY = "SOCKS5 127.0.0.1:62221; DIRECT";
    if ( %(cond)s ) return TUNNEL_PROXY;
    return "DIRECT";
}"""

import os
ipath = os.path.join(os.environ['HOME'], '.proxy.list')
opath = os.path.join(os.environ['HOME'], '.proxy.pac')

urls = filter(lambda x: len(x)!=0 and x[0]!='#',
              map(lambda x: x.strip(), 
                  open(ipath).readlines()))

import string
cond = string.join(map(lambda x: 'shExpMatch(url, "*%s*")'%(x), urls), "\n||")
pac = PAC%(globals())

open(opath,'w').write(pac)


