#!/usr/bin/env python
#coding:utf-8
#Copyright (C) dirlt

# install ubuntu packages.
import os
import string
import sys

def install():
    ORG = os.path.join(os.environ['HOME'],'repo/sperm/essay/ubuntu.org')
    xs = map(lambda x:string.strip(x),open(ORG).readlines())
    pkgs = []
    prefix = '- sudo apt-get install '
    for x in xs:    
        if(x.startswith(prefix)):
            x = x[len(prefix):]
            x = x.split('#')[0]
            pkgs.append(x)
    print pkgs
    cmd = 'sudo apt-get install %s'%(' '.join(pkgs))
    print cmd
    os.system(cmd)

if __name__ == '__main__':
    install()
